project_id = "mawznkkakikkjhwiwmde"
[functions.handle_new_user]
enabled = true
verify_jwt = true
import_map = "./functions/handle_new_user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/handle_new_user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/handle_new_user/*.html" ]
